[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
raydium_clmm = "G6QgP9DbJ2u4fAdi34xC7jAJzKTZERvT7sqmmkgjAC9D"

[programs.devnet]
raydium_clmm = "G6QgP9DbJ2u4fAdi34xC7jAJzKTZERvT7sqmmkgjAC9D"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"

