[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
raydium_clmm = "57wsvUhKGJU5bqcF2XaXQa2Jna8eSvF1nFcbfrFExXnH"

[programs.devnet]
raydium_clmm = "57wsvUhKGJU5bqcF2XaXQa2Jna8eSvF1nFcbfrFExXnH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"

